package ro.mpp2024.network.objectprotocol;

public enum RequestType {
    LOGIN, LOGOUT, GET_LOGGED_FRIENDS, SEND_MESSAGE,GET_PROBE,GET_PARTICIPANTI_DUPA_PROBE,GET_PROBE_DUPA_PARTICIPANT,INSCRIE,GET_NR_PARTICIPANTI;
}
