package ro.mpp2024.network.objectprotocol;

public enum ResponseType {
    OK, ERROR, GET_LOGGED_FRIENDS,UPDATE, NEW_MESSAGE, FRIEND_LOGGED_IN,FRIEND_LOGGED_OUT,GET_PROBE,GET_PARTICIPANTI_DUPA_PROBE,GET_PROBE_DUPA_PARTICIPANT,INSCRIE,GET_NR_PARTICIPANTI,NEW_INSCRIERE;

}